/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.matematicasDiscretas;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Inicializa la interfaz gráfica
        SimplexSolverGUI gui = new SimplexSolverGUI();
    }
}
